// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXOBwDEVisj6twDC-nMdY-p1FevwDaHQc',
    appId: '1:213841831999:web:1ec97d4fe3675f38e0708a',
    messagingSenderId: '213841831999',
    projectId: 'naturesync-7768e',
    authDomain: 'naturesync-7768e.firebaseapp.com',
    storageBucket: 'naturesync-7768e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk5wW5q_6P5ANZcDMYrGdYXTip3EhPZno',
    appId: '1:213841831999:android:6881edc96ccff4cde0708a',
    messagingSenderId: '213841831999',
    projectId: 'naturesync-7768e',
    storageBucket: 'naturesync-7768e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSimYnCTRwrOfgkqK3Nnpxo_J3MG1T9qw',
    appId: '1:213841831999:ios:22a3ceaaaf5daa01e0708a',
    messagingSenderId: '213841831999',
    projectId: 'naturesync-7768e',
    storageBucket: 'naturesync-7768e.firebasestorage.app',
    iosBundleId: 'com.example.csProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSimYnCTRwrOfgkqK3Nnpxo_J3MG1T9qw',
    appId: '1:213841831999:ios:22a3ceaaaf5daa01e0708a',
    messagingSenderId: '213841831999',
    projectId: 'naturesync-7768e',
    storageBucket: 'naturesync-7768e.firebasestorage.app',
    iosBundleId: 'com.example.csProjesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXOBwDEVisj6twDC-nMdY-p1FevwDaHQc',
    appId: '1:213841831999:web:bccac87fe1e35c9ae0708a',
    messagingSenderId: '213841831999',
    projectId: 'naturesync-7768e',
    authDomain: 'naturesync-7768e.firebaseapp.com',
    storageBucket: 'naturesync-7768e.firebasestorage.app',
  );
}
